### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by rachase** [lucascoelhof/unity-robot-teleoperation#3]
Do you by chance have a video of this working?  I am working on something similar and it would be good to see what other people are doing.  I am in the beginning stages.

**Comment by lucascoelhof** [comment]
Hi @drnobodyphd thanks for reaching us. And sorry for the late response, I've made the project private temporally because there was a lot of work in progress.

You can check the video of the VR application here https://www.youtube.com/watch?v=tMZiT0ObciI
This repository is not a framework, but a proof of concept, in which you can extract some ideas and use our implementations for your application (for example, the interface with ROS# and Oculus). It works with the ROS application available in https://github.com/lucascoelhof/voronoi_hsi
